### ISSUE TITLE
Can't install the module package 'PIL' system said that the pip version package not found.

### ISSUE THREAD

**Issue by rithik220** [protzermotzer/E6IMAGE#1]
C:\Users\home\PycharmProjects\Imagetagging>pip3 install PIL
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL
is there any alternate module package for this or please resolve this .

**Comment by protzermotzer** [comment]
My mistake, it should be `pip3 install pillow`.

(Or pip3.8 depending on what python version you're using)
